name: "CI: App"

on:
  push:
    branches: [main, develop]
    paths:
      - "**.ts"
      - "**.tsx"
      - "**.scss"
      - "**.js"
      - "**.mjs"
      - "**.css"
      - "**.json"
      - "**.yml"
  pull_request:
    types: [opened, synchronize]
    branches: [main, develop]
    paths:
      - "**.ts"
      - "**.tsx"
      - "**.scss"
      - "**.js"
      - "**.mjs"
      - "**.css"
      - "**.json"
      - "**.yml"
  workflow_dispatch:

jobs:
  code-tests:
    name: Test Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/setup-dependencies

      - name: Check formatting
        run: npm run prettier

      - name: Check lint
        run: npm run lint

      - name: Check types
        run: npm run types:check

      - name: Run tests
        run: npm run test:coverage
