name: Publish npm Package

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write # This allows pushing tags and commits
      packages: write # This allows publishing packages
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          # Fetch all history and tags
          fetch-depth: 0
          persist-credentials: true
          token: ${{ secrets.ACTIONS_PAT }}

      - uses: ./.github/actions/setup-dependencies

      - name: Run tests
        run: npm test

      - name: Build
        run: npm run build-lib

      - name: Version bump and push tag
        run: |
          # Configure git user
          git config user.name "missionmike"
          git config user.email "md@missionmike.dev"

          # Determine version bump type (you can adjust this logic)
          if git log -1 --pretty=%B | grep -q "\[major\]"; then
            npm version major
          elif git log -1 --pretty=%B | grep -q "\[minor\]"; then
            npm version minor
          else
            npm version patch
          fi

          # Push tag back to the repository
          git remote set-url origin https://x-access-token:${{ secrets.ACTIONS_PAT }}@github.com/mission-minded-llc/ampdresume-theme.git
          git push origin main --follow-tags

      - name: Setup .npmrc file
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

      - name: Publish to npm
        run: npm publish
